### ISSUE TITLE
gearbox help quickstart vs. gearbox quickstart -h

### ISSUE THREAD

**Issue by moschlar** [TurboGears/gearbox#1]
ATM, only `gearbox help quickstart` would bring up the help for the quickstart command, but IMO using `gearbox quickstart -h` or `gearbox quickstart --help` would be more intuitive (or if it at least told you where to look for the help text :D)

**Comment by amol-** [comment]
This is now solved by https://github.com/TurboGears/gearbox/commit/d9f143819516d56e7d836f971af7b9dc8aae841d
