### ISSUE TITLE
Error to execute gearbox setup-app when there is a top-level module without websetup module

### ISSUE THREAD

**Issue by evangilo** [TurboGears/gearbox#29]
Steps to reproduce:

1 - create a project using the "gearbox quickstart"
2 - create a new module called mymod in the root dir project
3 - execute "pip install -e ."
4 - execute "gearbox setup-app -c development.ini"

After it you should see the bellow error:

```
root@4175eeb480ae:/myproj# gearbox setup-app -c development.ini 
No module named 'mymod.websetup'
12:17:42,701 ERROR [gearbox] No module named 'mymod.websetup'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gearbox/main.py", line 172, in _run_subcommand
    return cmd.run(parsed_args)
  File "/usr/local/lib/python3.9/site-packages/gearbox/command.py", line 31, in run
    self.take_action(parsed_args)
  File "/usr/local/lib/python3.9/site-packages/gearbox/commands/setup_app.py", line 53, in take_action
    self._setup_config(dist, config_file, section, {}, verbosity=self.app.options.verbose_level)
  File "/usr/local/lib/python3.9/site-packages/gearbox/commands/setup_app.py", line 79, in _setup_config
    mod = self._import_module(mod_name)
  File "/usr/local/lib/python3.9/site-packages/gearbox/commands/setup_app.py", line 114, in _import_module
    mod = __import__(s)
ModuleNotFoundError: No module named 'mymod.websetup'
```
This issue happens only on python 3.

**Comment by amol-** [comment]
Well, `setup-app` is the command meant to run the `websetup`. If there is no `websetup` it can't do anything. I guess we can easily improve the error message, but if you  don't have a websetup you can avoid invoking setup-app at all.

**Comment by evangilo** [comment]
The problem is that my application has one module with the websetup and many other modules without the websetup, so when I invoke the setup-app this error happens. I was reading the code and I think that there is a bug at https://github.com/TurboGears/gearbox/blob/27bf236235942b745dc5de01fb98293ca2e67b9c/gearbox/commands/setup_app.py#L83 because the exception message is different on python 3, on python 2 the error message will be `No module named websetup` and on python 3 will be `No module named 'mymod.websetup'`. 

If this issue is valid I can open a PR to fix it.
