### ISSUE TITLE
Tempita dependency uses cgi and is thus not compatible with Python 3.13

### ISSUE THREAD

**Issue by kiilerix** [TurboGears/gearbox#33]
Gearbox depends on https://pypi.org/project/Tempita/ which seems to be quite dead. http://pythonpaste.org/tempita/ doesn't work and I don't know if they have an issue tracker.

tempita uses cgi.escape . cgi was removed in Python 3.13 . Gearbox and TurboGears thus doesn't seem to support Python 3.13 .

**Comment by kiilerix** [comment]
https://github.com/Pylons/webob/issues/437 is also a problem for proper support for Python 3.13 .

In both cases, it can be worked around by installing `legacy-cgi` from pypi.

**Comment by amol-** [comment]
`cgi` removal has been a TODO for a while, removing it in TurboGears and associated projects is easy, but so far the blocker has been WebOb. Until WebOb removes CGI dependency, it doesn't make much sense for TurboGears to do so.

**Comment by kiilerix** [comment]
But since WebOb didn't catch up yet, it might be a dead dependency that will have to be replaced by something else.

**Comment by amol-** [comment]
> But since WebOb didn't catch up yet, it might be a dead dependency that will have to be replaced by something else.

I think that including https://pypi.org/project/legacy-cgi/ in the dependencies of TurboGears might be a reasonable fix for the moment. I'll try to reach to WebOb maintainers and see what's blocking the removal.

Regarding Tempita, there is a TurboGears fork: https://github.com/TurboGears/tempita and I'm already talking with maintainers to get permissions to cut releases.

**Comment by amol-** [comment]
Tempita 0.6.0 has been released on PyPi and no longer depends on `cgi` module
